#version: "3.9"

services:
  app:
    build: ./app
    container_name: dojo_app
    restart: always
    depends_on:
      - db
          condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: dojo_user
      DB_PASSWORD: dojo_pass
      DB_NAME: dojo_presencas
    networks:
      - rede_compartilhada
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:latest
    container_name: dojo_nginx
    restart: always
    ports:
      - "9081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - app
    networks:
      - rede_compartilhada

  db:
    image: mysql:8.0
    container_name: dojo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dojo_presencas
      MYSQL_USER: dojo_user
      MYSQL_PASSWORD: dojo_pass
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/estrutura.sql:/docker-entrypoint-initdb.d/estrutura.sql:ro
    networks:
      - rede_compartilhada

  adminer:
    image: adminer:latest
    container_name: dojo_adminer
    restart: always
    ports:
      - "9082:8080"
    networks:
      - rede_compartilhada

networks:
  rede_compartilhada:
    driver: bridge
    external: true

volumes:
  mysql_data:
  static_volume:
